# example.ini

# Comment using '#'
; or using ';'
; Inline comments are not supported yet.
; Pull requests are welcome.

[user]

first_name = "Mumflr"
last_name = "Fumperdink"
age = 36

# Enums can be quoted or unquoted. Upto you.
day_of_birth = wednesday
month_of_birth = "june"
show_desktop_info = true

[desktop]

bg_color = "#00FFFF"
wallpaper_path = "~/Pictures/Walls/Cat.png"
window_manager_kind = "dynamic"

# You can split section into multiple parts like this:

[desktop]

opacity = 0.8
width = 1377
height = 6969

# If duplicate entries are found, lastest one is used.
height = 768

# dynamic section. Try adding more.
[messages]
Walter = "Jesse, we need to cook."
Jesse = "Aaaahhh Wire..."
Hank = "Jesus Christ Marie! They're minerals!"
Saul = "It's all good man."
Hector = "🛎️🛎️🛎️🛎️"
Gus = "HAAAAAAAAA!"
